spring:
  application:
    name: mall-admin
  profiles:
    active: dev #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#mybatis:
#  mapper-locations:
#    - classpath:dao/*.xml
#    - classpath*:com/**/mapper/*.xml

mybatis-plus:
  mapper-locations: classpath*:com/liu/mall/mapper/**/*.xml #指定mapper.xml路径,不指定自定义的sql找不到
  global-config:
    db-config:
      id-type: auto #全局默认主键类型设置为自增
  configuration:
    auto-mapping-behavior: partial #只对非嵌套的 resultMap 进行自动映射
    map-underscore-to-camel-case: true #开启自动驼峰命名规则映射
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-user-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

redis:
  database: mall
  key:
    user: "User"
    prefix:
      authCode: "portal:authCode:"
      inventory: "user:inventoryQueue"
    expire:
      authCode: 12000 # 验证码超期时间
  expire:
    common: 21600 # 6小时


secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /minio/upload
      - /androidUser/getAuthCode
      - /androidUser/login
      - /androidUser/getByUsername
      - /androidArticle/**


aliyun:
  oss:
    endpoint: https://oss-cn-guangzhou.aliyuncs.com # oss对外服务的访问域名
    bucketName: silvery # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://39.98.190.128:8080/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: mall/images/ # 上传文件夹路径前缀
